config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  get 'home/search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@stories = StoryService.new(params).fetch
  end

  def search
  	@stories = StoryService.new(params).fetch
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_results.html.erb
<div class="row">
    <div class="col-12 col-md-10 col-lg-8">
		<%@stories.each do |story|%>
			<div class="card">
				<h6>
					<%= link_to "#{story['title']}", story['url'] %>
				</h6>
				<div class="card-body">
					By: <%= story['author']%>
		
				</div>
			</div>
			<br>
		<% end %>
    </div>
</div>

app/views/layouts/_header.html.erb
<div class="row justify-content-center">
    <div class="">
        <h3>Welcome to Hacker News Stories</h3>
        <p>Giving you all latest stories at your finger tips!!</p>
    </div>
</div>
<div class="row justify-content-center">
    <div class="col-12 col-md-10 col-lg-8">
        <div class="">
            <div class="card-body row no-gutters align-items-center">
                <div class="col-auto">
                    <i class="fas fa-search h4 text-body"></i>
                </div>
                <%= form_tag(home_search_path, :method => "get", id: "search-form") do %>
	                <div class="col">
	                	<%= text_field_tag :search, params[:search], placeholder: "Search news", class: 'form-control form-control-lg',
	                	type: "search" %>
	                </div>
	                <div class="col-auto">
	                	<%= submit_tag "Search", class: 'btn btn-lg btn-success' %>
	                </div>
	            <% end %>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HackernewsStories</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render partial: 'layouts/header' %>
      <br>
      <%= render partial: 'results' %>
    </div>
    <%= yield %>
  </body>
</html>